# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6c1a39944a4ab6bdd6e4428ccceb028b"
name = "new"
application_url = "https://craft-called-future-place.trycloudflare.com/"
embedded = true
handle = "new-270"

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://craft-called-future-place.trycloudflare.com/auth/callback",
  "https://craft-called-future-place.trycloudflare.com/auth/shopify/callback",
  "https://craft-called-future-place.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://automatic-learners-excluded-decorative.trycloudflare.com/storefront/subscription"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
