# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cf03fe5e07a942b9d58fc9815aa65d69"
name = "latest-app"
application_url = "https://install-newcastle-desert-computation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://install-newcastle-desert-computation.trycloudflare.com/api/auth",
  "https://install-newcastle-desert-computation.trycloudflare.com/api/auth/callback"
]
